version: "3"

services:
  movie_service:
    build: movie_service
    ports:
      - "5001:5000"
    depends_on:
      - rating_service
    networks:
      - app_network

  rating_service:
    build: rating_service
    ports:
      - "5002:5000"
    networks:
      - app_network

networks:
  app_network:
